version: "3.7"

services:
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on: 
      - redis
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8082:8081

  server:
    build: './server'
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:6379
    ports: 
      - 4000:4000

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    depends_on:
      - server
    ports:
      - "3000:80"
    