name: Deploy frontend

on:
  push:
    branches: [main]
    paths: ["client/**"]

  workflow_dispatch:

jobs:
  Build-n-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy frontend to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "lyrson-client"
          heroku_email: janekkacperczyk@gmail.com
          appdir: "client"
