name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  Build-n-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy backend to heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "lyrson-server"
          heroku_email: "janekkacperczyk@gmail.com"
          appdir: "server"
